ALTER TABLE TB_AGENDAMENTO
    ADD COLUMN IF NOT EXISTS ID_USUARIO BIGINT;

UPDATE TB_AGENDAMENTO a
SET ID_USUARIO = v.ID_USUARIO
    FROM TB_VEICULO v
WHERE a.ID_VEICULO = v.ID_VEICULO
  AND a.ID_USUARIO IS NULL;

UPDATE TB_AGENDAMENTO
SET ID_USUARIO = 1
WHERE ID_USUARIO IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_agendamento_usuario'
    ) THEN
ALTER TABLE TB_AGENDAMENTO
    ADD CONSTRAINT FK_AGENDAMENTO_USUARIO
        FOREIGN KEY (ID_USUARIO)
            REFERENCES TB_USUARIOS (ID);
END IF;
END $$;