ALTER TABLE TB_AGENDAMENTO
    ADD COLUMN IF NOT EXISTS ID_MECANICO BIGINT;

ALTER TABLE TB_AGENDAMENTO
DROP CONSTRAINT IF EXISTS FK_AGENDAMENTO_MECANICO;

ALTER TABLE TB_AGENDAMENTO
    ADD CONSTRAINT FK_AGENDAMENTO_MECANICO
        FOREIGN KEY (ID_MECANICO)
            REFERENCES TB_USUARIOS(ID);