ALTER TABLE TB_AGENDAMENTO
    ADD COLUMN IF NOT EXISTS ID_SERVICO BIGINT;

ALTER TABLE TB_AGENDAMENTO
DROP CONSTRAINT IF EXISTS FK_AGENDAMENTO_SERVICO;

ALTER TABLE TB_AGENDAMENTO
    ADD CONSTRAINT FK_AGENDAMENTO_SERVICO
        FOREIGN KEY (ID_SERVICO)
            REFERENCES TB_SERVICO(ID);