CREATE TABLE IF NOT EXISTS TB_AGENDAMENTO_EVENTO (
                                                     ID BIGSERIAL PRIMARY KEY,
                                                     ID_AGENDAMENTO BIGINT NOT NULL,
                                                     TITULO VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(500),
    STATUS VARCHAR(30) NOT NULL,
    DATA_EVENTO TIMESTAMP NOT NULL,
    ID_CRIADO_POR BIGINT,

    CONSTRAINT FK_AGENDAMENTO_EVENTO_AGENDAMENTO
    FOREIGN KEY (ID_AGENDAMENTO)
    REFERENCES TB_AGENDAMENTO(ID_AGENDAMENTO),

    CONSTRAINT FK_AGENDAMENTO_EVENTO_USUARIO
    FOREIGN KEY (ID_CRIADO_POR)
    REFERENCES TB_USUARIOS(ID),

    CONSTRAINT TB_AGENDAMENTO_EVENTO_STATUS_CHECK
    CHECK (STATUS IN (
           'PENDENTE',
           'AGENDADO',
           'CONFIRMADO',
           'EM_ANDAMENTO',
           'QUASE_FINALIZADO',
           'FINALIZADO',
           'CANCELADO'
                     ))
    );